export const Condition = {
  // 출석 관련
  ATTENDANCE_DAYS_3: 'ATTENDANCE_DAYS_3',
  ATTENDANCE_DAYS_7: 'ATTENDANCE_DAYS_7',
  ATTENDANCE_DAYS_30: 'ATTENDANCE_DAYS_30',
  CONSECUTIVE_DAYS_3: 'CONSECUTIVE_DAYS_3',
  CONSECUTIVE_DAYS_7: 'CONSECUTIVE_DAYS_7',
  CONSECUTIVE_DAYS_14: 'CONSECUTIVE_DAYS_14',
  DAILY_LOGIN: 'DAILY_LOGIN',
  LOGIN_TODAY: 'LOGIN_TODAY',
  LOGIN_COUNT_OVER_10: 'LOGIN_COUNT_OVER_10',

  // 포인트 사용
  USED_POINTS_OVER_500: 'USED_POINTS_OVER_500',
  USED_POINTS_OVER_1000: 'USED_POINTS_OVER_1000',

  // 아이템 수집
  ITEM_COLLECTED_SET_COMPLETE: 'ITEM_COLLECTED_SET_COMPLETE',
  ITEM_RARE_ACQUIRED: 'ITEM_RARE_ACQUIRED',

  // 친구 초대
  FRIEND_INVITE_EVERY_10: 'FRIEND_INVITE_EVERY_10',

  // 리워드 획득
  REWARD_ACQUIRED_ONLY: 'REWARD_ACQUIRED_ONLY',
  REWARD_COUNT_OVER_10: 'REWARD_COUNT_OVER_10',
} as const;

export type ConditionType = (typeof Condition)[keyof typeof Condition];
